Private events
Ralph-1/Private pull request #1
Opened 2021-03-14 21:03 UTC by Ralph-1

### In this project, I built an application named Private Events and that behaves similarly to Eventbrite. The main goal is to put in practice the main concepts of Associations in rails.

I made sure that:

- all foreign keys have corresponding indexes in the Database, as it will make your database performance better.

- test our code using Rspec and Capybara

2021-03-14 21:26 UTC, Ralph-1 commented
I changed the project repository because the codebase was messed up and created a new repo and started the project a fresh. This is the [link](https://github.com/Ralph-1/Private__events/pull/2) to the old pull request

2021-03-14 23:28 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

### Hello @Ralph-1, great job here, the application works just as expected and your UI looks great. 👏 
Well done on writing tests, good coverage 👍 
Let's make a few changes, and we will be done.

- [ ] Handle validation errors properly in your controller as entering a location below the minimum requirement throws an error. Also note 5 is too much for minimum, Example name of the city I live is called Uyo, meaning I can't enter that as a valid location. 

- [ ] There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it.  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright)
I have gone ahead and made some comments on your codebase see affected files below:

**Don't know where to start or how to?** See  [Rails View Helpers Best Practices](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4) 

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla) or reply to this thread, if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2021-03-14 23:28 UTC, acushlakoncept commented on app/views/events/_form.html.erb
> +          </div>
There should be absolutely NO logic in views.

2021-03-14 23:28 UTC, acushlakoncept commented on app/views/layouts/application.html.erb
> +          <% end %>
There should be absolutely NO logic in views.

2021-03-15 06:45 UTC, peterrobert requested changes
### CHANGES REQUIRED ♻️ 🛑 
Hello, @Ralph-1  👋🏿 . Great work making the changes that were requested by the previous TSE. Also, great work with the application. It almost meet all the requirements. However, for your project to be approved, you need to do some additional changes kindly check below ⬇️ 

- [ ] Kindly remove all the logic from your views. The views should only be for displaying information. Any logic should be created in the helpers.

### if you have any question kindly reach me on slack @peterrobert


### HAPPY CODING 💻

2021-03-15 06:45 UTC, peterrobert commented on app/views/events/index.html.erb
> +          <% end %>
- [ ] There should absolutely be no logic in your views. Views are only for displaying information that became available to it from its corresponding controller. Kindly use this [resource](http://codefol.io/posts/Where-Do-I-Put-My-Code/) to learn more on this.

- Kindly use the rails helpers for your logic. Logic includes, Loops and If statements.

2021-03-15 06:45 UTC, peterrobert commented on app/views/events/index.html.erb
> +            Event Details
- [ ] There should absolutely be no logic in your views. Views are only for displaying information that became available to it from its corresponding controller. Kindly use this [resource](http://codefol.io/posts/Where-Do-I-Put-My-Code/) to learn more on this.

- Kindly use the rails helpers for your logic. Logic includes, Loops and If statements.

2021-03-15 06:45 UTC, peterrobert commented on app/views/events/show.html.erb
> +  <% end %>
- [ ] There should absolutely be no logic in your views. Views are only for displaying information that became available to it from its corresponding controller. Kindly use this [resource](http://codefol.io/posts/Where-Do-I-Put-My-Code/) to learn more on this.

- Kindly use the rails helpers for your logic. Logic includes, Loops and If statements.

2021-03-15 10:34 UTC, acushlakoncept approved these changes
# Status: PROJECT APPROVED  🎉 🚀

### Hi, @Ralph-1  well done on this project, I am sure you're feeling more and more confident in tackling Ruby-on-Rails project.

I will go ahead and mark this as complete, feel free to merge when you are ready. All the best with the next project.


### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2021-03-15 11:43 UTC, merged